services:
  - type: web
    name: trainline
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: FLASK_ENV
        value: production
